[package]
name = "uniffi"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
# Re-exported dependencies used in generated Rust scaffolding files.
anyhow = "1"
bytes = "0.5"
ffi-support = "0.4.0"
lazy_static = "1.4"
log = "0.4"
# Regular dependencies
# cargo_metadata = { git = "https://github.com/oli-obk/cargo_metadata", rev = "64ee6d1d169103ed60ae4de5ddf84da751e7d841" }
paste = "0.1"
uniffi_bindgen = { path = "../uniffi_bindgen", optional = true }

[features]
default = []
# Use the `uniffi_bindgen` from this workspace instead of the one installed on your system.
# You probably only want to enable this feature if you're working on uniffi itself.
builtin-bindgen = ["uniffi_bindgen"]
