[package]
name = "uniffi_build"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
# cargo_metadata = { git = "https://github.com/oli-obk/cargo_metadata", rev = "64ee6d1d169103ed60ae4de5ddf84da751e7d841" }
anyhow = "1"
uniffi_bindgen = { path = "../uniffi_bindgen", optional = true }

[features]
default = []
# Use the `uniffi_bindgen` from this workspace instead of the one installed on your system.
# You probably only want to enable this feature if you're working on uniffi itself.
builtin-bindgen = ["uniffi_bindgen"]
